import React from 'react';
import ReactDOM from 'react-dom';
import App from './App'
import 'bootstrap/dist/css/bootstrap.min.css';
import './index.css'

import './assets/tpb.mp3'

import './assets/felt.jpg'
import './assets/10C.png'
import './assets/10D.png'
import './assets/10H.png'
import './assets/10S.png'
import './assets/2C.png'
import './assets/2D.png'
import './assets/2H.png'
import './assets/2S.png'
import './assets/3C.png'
import './assets/3D.png'
import './assets/3H.png'
import './assets/3S.png'
import './assets/4C.png'
import './assets/4D.png'
import './assets/4H.png'
import './assets/4S.png'
import './assets/5C.png'
import './assets/5D.png'
import './assets/5H.png'
import './assets/5S.png'
import './assets/6C.png'
import './assets/6D.png'
import './assets/6H.png'
import './assets/6S.png'
import './assets/7C.png'
import './assets/7D.png'
import './assets/7H.png'
import './assets/7S.png'
import './assets/8C.png'
import './assets/8D.png'
import './assets/8H.png'
import './assets/8S.png'
import './assets/9C.png'
import './assets/9D.png'
import './assets/9H.png'
import './assets/9S.png'
import './assets/AC.png'
import './assets/AD.png'
import './assets/AH.png'
import './assets/AS.png'
import './assets/JC.png'
import './assets/JD.png'
import './assets/JH.png'
import './assets/JS.png'
import './assets/KC.png'
import './assets/KD.png'
import './assets/KH.png'
import './assets/KS.png'
import './assets/QC.png'
import './assets/QD.png'
import './assets/QH.png'
import './assets/QS.png'
import './assets/blue_back.png'
import './assets/gray_back.png'
import './assets/green_back.png'
import './assets/purple_back.png'
import './assets/red_back.png'
import './assets/yellow_back.png'

ReactDOM.render(<App />, document.getElementById('app'));
