import React from 'react';
import ReactDOM from 'react-dom';
import App from './App'
import 'bootstrap/dist/css/bootstrap.min.css';
import './index.css'

import './cards/10C.png'
import './cards/10D.png'
import './cards/10H.png'
import './cards/10S.png'
import './cards/2C.png'
import './cards/2D.png'
import './cards/2H.png'
import './cards/2S.png'
import './cards/3C.png'
import './cards/3D.png'
import './cards/3H.png'
import './cards/3S.png'
import './cards/4C.png'
import './cards/4D.png'
import './cards/4H.png'
import './cards/4S.png'
import './cards/5C.png'
import './cards/5D.png'
import './cards/5H.png'
import './cards/5S.png'
import './cards/6C.png'
import './cards/6D.png'
import './cards/6H.png'
import './cards/6S.png'
import './cards/7C.png'
import './cards/7D.png'
import './cards/7H.png'
import './cards/7S.png'
import './cards/8C.png'
import './cards/8D.png'
import './cards/8H.png'
import './cards/8S.png'
import './cards/9C.png'
import './cards/9D.png'
import './cards/9H.png'
import './cards/9S.png'
import './cards/AC.png'
import './cards/AD.png'
import './cards/AH.png'
import './cards/AS.png'
import './cards/JC.png'
import './cards/JD.png'
import './cards/JH.png'
import './cards/JS.png'
import './cards/KC.png'
import './cards/KD.png'
import './cards/KH.png'
import './cards/KS.png'
import './cards/QC.png'
import './cards/QD.png'
import './cards/QH.png'
import './cards/QS.png'
import './cards/blue_back.png'
import './cards/gray_back.png'
import './cards/green_back.png'
import './cards/purple_back.png'
import './cards/red_back.png'
import './cards/yellow_back.png'

ReactDOM.render(<App />, document.getElementById('app'));
